version: '3'
services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./certbot/www:/var/www/certbot
    networks:
      - proxy-network
    restart: always
    
# generate/renewal ssl certificat for lomfabrizio.duckdns.org
#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./letsencrypt:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    entrypoint: sh -c "sleep 5 && certbot certonly --webroot -w /var/www/certbot --email lomfabrizio@hotmail.com --agree-tos --no-eff-email --force-renewal -d lomfabrizio.duckdns.org"
#    depends_on:
#      - nginx-proxy 
#    networks:
#        - proxy-network


# generate/renewal ssl certificat for tastytrack.duckdns.org
#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./letsencrypt:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    entrypoint: sh -c "sleep 5 && certbot certonly --webroot -w /var/www/certbot --email lomfabrizio@hotmail.com --agree-tos --no-eff-email --force-renewal -d tastytrack.duckdns.org"
#    depends_on:
#      - nginx-proxy 
#    networks:
#        - proxy-network

networks:
  proxy-network:
    driver: bridge